### ISSUE TITLE
Request Tokyo Xanadu

### ISSUE THREAD

**Issue by InitialXKO** [Electry/VitaGrafixPatchlist#10]
```
# Tokyo Xanadu [JP 1.04]
[PCSG00608,eboot.bin]
@IB
0:0xE75C8 t2_mov(1,1,<ib_w>)
0:0xE75CC t2_mov(1,2,<ib_h>)
0:0xE7602 t2_mov(1,1,<ib_w>)
0:0xE7606 t2_mov(1,2,<ib_h>)
# Tokyo Xanadu [ASIA 1.00]
[PCSH10009,eboot.bin]
@IB
0:0xE7A48 t2_mov(1,1,<ib_w>)
0:0xE7A4C t2_mov(1,2,<ib_h>)
0:0xE7A82 t2_mov(1,1,<ib_w>)
0:0xE7A86 t2_mov(1,2,<ib_h>)
```

**Comment by yeqing1990** [comment]
The resolution of this game is changed to 1280x720, and the display is best. You can also change the low point, such as 1280x544, and the number of frames may be higher.

**Comment by Caliburnflash** [comment]
Does it work on pcse00893?

**Comment by BOBdotEXE** [comment]
> Does it work on pcse00893?

Nope, tried both the JP, and Asia patches, both crash the game.
 
I'd imagine the USA release is based on the Asia 1.0 version, with some slight tweaks for English text, but I can't say for sure.

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/0ecce1396268556815f6af64b32fbbe990331413

IB=960x544 with the new patch is equivalent to IB=1280x720 with the one posted here
