### ISSUE TITLE
Uncharted PCSF00001 Your game version is not supported?

### ISSUE THREAD

**Issue by JmsMtthw** [Electry/VitaGrafixPatchlist#119]
Hiya, what should I do to remove this error? this is what the log says btw 
![159477349_4134857293200303_7555749158005449970_n](https://user-images.githubusercontent.com/80386007/110598566-de661980-81bc-11eb-8e3f-55be7ed83fdf.jpg)

**Comment by of-ravens-claw** [comment]
Update your game via the livearea to 1.03

**Comment by JmsMtthw** [comment]
So updating it via a dump will also give this error?

**Comment by of-ravens-claw** [comment]
I'm not sure on what you mean, but updating a NoNpDrm dump works fine

**Comment by JmsMtthw** [comment]
I meant if you patch it also via a Dump it will not work. But I downloaded version 1.0 and then updated it via Live Area and it works.
