### ISSUE TITLE
[HELP] Failed to parse patchlist Edit: Need for Speed Most Wanted

### ISSUE THREAD

**Issue by ElMogueta** [Electry/VitaGrafixPatchlist#123]
Hello everybody, I'm having this issue while trying to use VitaGrafix

Here's a screenshot of the log (got confused and posted it for another game, error is the same tho)

![IMG_20210513_173119](https://user-images.githubusercontent.com/84158075/118195577-14b85300-b411-11eb-9fc2-5c1f6adb40a1.jpg)

Tried to google the error but got no results
Thanks in advance!

EDIT

Apparently the error is caused by setting a resolution on Need for Speed Most Wanted, disabling VitaGrafix for that game solves the problem

EDIT 2: 

Reinstalled everything at it worked again

**Comment by Masamune3210** [comment]
if I'm understanding the error correctly, it's complaining that more than one entry is trying to modify the same bit of memory

**Comment by ElMogueta** [comment]
> if I'm understanding the error correctly, it's complaining that more than one entry is trying to modify the same bit of memory

Checked the line and it refers to both different codes.
Here's proof 
![IMG_20210513_194950](https://user-images.githubusercontent.com/84158075/118204703-746c2980-b424-11eb-9e2c-7d2460033886.jpg)
