### ISSUE TITLE
[BUG] Minecraft (PCSB00560) stuck on boot screen

### ISSUE THREAD

**Issue by MinikPLayer** [Electry/VitaGrafixPatchlist#15]
When VitaGrafix enabled the game is stuck on the boot screen ( the boot is like this: start -> that logo with some mobs -> black screen and game running, and it's stuck on the 2nd part ).

Disabling VitaGrafix of course fixes the problem. Also, leaving only FPS set to 30 the game also works. Changing FB is the cause of the problem

Spec:
PS VITA 1000 OLED 3.68
Minecraft 1.82
VitaGrafix 4.0

**Comment by MinikPLayer** [comment]
EDIT: It looks like the problem is only when setting resolution higher than default, with 640x368 it works fine

**Comment by Electry** [comment]
I just tried PCSB00560 and haven't had any issues (at 960x544).
Is it crashing only with a particular game save?

**Comment by MinikPLayer** [comment]
Sorry for trouble, i've accidentally typed 960x540 instead of 960x544. Now works fine, thanks for help!

**Comment by Electry** [comment]
np
