### ISSUE TITLE
[REQUEST] Blue Reflection (PCSG-00987)

### ISSUE THREAD

**Issue by Doredialilligan** [Electry/VitaGrafixPatchlist#19]
As most of you may know, this game and literally all Gust games are so bad in framerate. It would be great if we could downgrade the resolution in order to have a improvement in the framerate. These are the resolutions ofsets for Blue Reflection 1.05 ver.

seg000:81314F60 MOVS.W R0, #0x3C0
seg000:81314F66 MOVS.W R0, #0x220

seg000:81314F54 MOVS.W R0, #0x3C0
seg000:81314F5A MOVS.W R0, #0x1BA

seg000:81314F48 MOVS.W R0, #0x3C0
seg000:81314F4E MOVS.W R0, #0x220

I can´t do it by myself because the last part of the guide [here](http://psvita.chvila.sk/guides/) is not up yet. In the future, I will do all Atelier games as well as Night of Azure I & II :)

**Comment by Electry** [comment]
it's easy :P

seg000 -> 0
81314F60 in seg000 -> 0x314F60
MOVS.W -> t2_mov(1,x,<ib_w>) where x is the the register (in this case R0 -> 0)

so the first one will be:

`0:0x314F60 t2_mov(1,0,<ib_w>)`

Check [here](https://github.com/Electry/VitaGrafix/blob/master/README.md) for more info on the patchlist syntax.

**Comment by Doredialilligan** [comment]
Thank you so much @Electry :)
These offsets are for the game without update, so these are the real offsets for 1.05 ver.

seg000:81317160  MOVS.W  R0, #0x3C0
seg000:81317166  MOVS.W  R0, #0x220

seg000:8131716C  MOVS.W  R0, #0x3C0
seg000:81317172  MOVS.W  R0, #0x1BA

seg000:81317178   MOVS.W  R0, #0x3C0
seg000:8131717E   MOVS.W  R0, #0x220

I've been able to patch 1st and 3rd pair of offsets to 720x408 and the fps are a bit better, but I can´t patch the 2nd pair of offsets because it give me an error. In VGi I saw that the 2nd pair resolution (960x442) have a 4x MSAA and I don't know to to do that. In 720x408 the game looks cutted by the edges of the screen and I think that it's for that extrange resolution that I can't patch.

Could ypu please help me @Electry ? :)

**Comment by Doredialilligan** [comment]
![2019-01-15-132016](https://user-images.githubusercontent.com/23343800/51180261-4617c700-18c8-11e9-92d9-c27a3c72407f.jpg)
This is how the game looks like with the 1st and 3rd pair of offsets patched at 720x408

**Comment by Accelerator11** [comment]
You should leave 1st and 3rd pair of offset. Only use the 2nd pair of offset

seg000:8131716C MOVS.W R0, #0x3C0
seg000:81317172 MOVS.W R0, #0x1BA

Atelier Shallie, Firis, Night of Azure 2, Lydle and Suelle uses same internal resolution (960x442).

**Comment by Doredialilligan** [comment]
But how can I dissable MSAA? @Electry @Accelerator11

**Comment by Accelerator11** [comment]
Setting it lower than width 960 will crash the game.

**Comment by Doredialilligan** [comment]
Thank you @Accelerator11 !
With 960x368 resolution it does't seem to give a fps improvement. I think that the MSAA x4 is what is giving the game that bad framerate. Is the any way to get rid of MSAA?

Let's invoke @Electry for his knowledge :3

**Comment by Accelerator11** [comment]
I don't know about changing the MSAA. Anyway 442 to 368 isn't going to do much difference in fps.

**Comment by Doredialilligan** [comment]
Any help please? @Electry @ImplyingKinpatsu @yeqing1990

**Comment by Electry** [comment]
```
# Blue Reflection [JP 1.05]
[PCSG00987,eboot.bin,0xB2361C99]
@MSAA
0:0x71DFD8 uint32(<msaa>)
```
I wouldn't expect much higher fps even with msaa off.

**Comment by Doredialilligan** [comment]
Thank you so much @Electry !

With MSAA 1x I see a difference of 1-2 fps. It´s sad that this game can´t run better even with tweaks. The last thing could be the Parameter Buffer Size. It is 33,55Mb, the double of a normal parameter buffer size, but I don't know if it would give the game a bit of help.

Could you please tell me how you found the MSAA offset? I would do the same for Atelier games in order to try them to run a bit better :)

**Comment by Electry** [comment]
I searched where sceGxmColorSurfaceInit() was called from.

![image](https://user-images.githubusercontent.com/12598379/52538807-4bf1b280-2d77-11e9-9ee9-059d8144ee11.png)

As you can see by looking at xrefs (click on sceGxmColorSurfaceInit and press X), it is only called from one location, sub_810E43DA().

```
int sceGxmColorSurfaceInit(
	SceGxmColorSurface *surface,
	SceGxmColorFormat colorFormat,
	SceGxmColorSurfaceType surfaceType,
	SceGxmColorSurfaceScaleMode scaleMode,
	SceGxmOutputRegisterSize outputRegisterSize,
	unsigned int width,
	unsigned int height,
	unsigned int strideInPixels,
	void *data);

typedef enum SceGxmColorSurfaceScaleMode {
	SCE_GXM_COLOR_SURFACE_SCALE_NONE           = 0x00000000u,
	SCE_GXM_COLOR_SURFACE_SCALE_MSAA_DOWNSCALE = 0x00000001u
} SceGxmColorSurfaceScaleMode;
```

sceGxmColorSurfaceInit() takes scaleMode as 4th parameter, which can either be 0 (no msaa) or 1 (msaa downscale). Decompiling sub_810E43DA() func can quickly show you how is it set.

![image](https://user-images.githubusercontent.com/12598379/52538837-b4d92a80-2d77-11e9-9b64-fcf7803d4cd1.png)

scaleMode (v16) is set to 1 if v25 is positive.

v25 is result of sub_81239F78(), which takes one parameter, and index of some sort, which can only be 0, 1, 2 or 3 (v6 is some value ANDed with 3, as you can see below).

![image](https://user-images.githubusercontent.com/12598379/52538917-9f183500-2d78-11e9-90bc-f97d4928f821.png)

![image](https://user-images.githubusercontent.com/12598379/52538983-907e4d80-2d79-11e9-85dc-977642940d3c.png)

By substituting a1 with 0 we get 2^32 + (4 * 0 - 0x7E8E2030) = 0x8171DFD0. 

![image](https://user-images.githubusercontent.com/12598379/52539070-2dd98180-2d7a-11e9-8a81-87871955bf92.png)

these align with SceGxmMultisampleMode, which can be confirmed by looking at where else and how is sub_81239F78() used (hint: inside of sub_81243506() => sceGxmShaderPatcherCreateFragmentProgram() which takes SceGxmMultisampleMode)

```
typedef enum SceGxmMultisampleMode {
	SCE_GXM_MULTISAMPLE_NONE = 0,
	SCE_GXM_MULTISAMPLE_2X = 1,
	SCE_GXM_MULTISAMPLE_4X = 2
} SceGxmMultisampleMode;
```

We know it's 4x MSAA so we change 8171DFD8 value.

**Comment by Doredialilligan** [comment]
Its so hard for me to understand and reproduce all these steps, I'm stuck when you decompile sub_810E43DA() and you get this:
```
 int sceGxmColorSurfaceInit(
	SceGxmColorSurface *surface,
	SceGxmColorFormat colorFormat,
	SceGxmColorSurfaceType surfaceType,
	SceGxmColorSurfaceScaleMode scaleMode,
	SceGxmOutputRegisterSize outputRegisterSize,
	unsigned int width,
	unsigned int height,
	unsigned int strideInPixels,
	void *data);

typedef enum SceGxmColorSurfaceScaleMode {
	SCE_GXM_COLOR_SURFACE_SCALE_NONE           = 0x00000000u,
	SCE_GXM_COLOR_SURFACE_SCALE_MSAA_DOWNSCALE = 0x00000001u
} SceGxmColorSurfaceScaleMode;
```

**Comment by Electry** [comment]
That's a snippet from [vitasdk](https://github.com/vitasdk/vita-headers/blob/master/include/psp2/gxm.h#L1382). sceGxmColorSurfaceInit() is a function within the vita's SceGxm library. A game calls it to prepare a color surface.

I just wanted to show you that it takes a parameter called "scaleMode" which indicates whether MSAA is used or not. We can use this to trace back where the MSAA value is stored.

Decompiled sub_810E43DA() is the screenshot below that.

**Comment by Doredialilligan** [comment]
I just noticed that with MSAA 1x and 2x there are some glitches in the game. During battles or when you are in the blue portals of The Common, the effects starts to flicker and they seems to be cutted in half.
![2019-02-10-230119](https://user-images.githubusercontent.com/23343800/52540309-6da76580-2d88-11e9-82a8-226e8effe9c2.png)
![2019-02-10-225909](https://user-images.githubusercontent.com/23343800/52540312-7435dd00-2d88-11e9-853e-be1e52547a04.png)
![2019-02-10-225919](https://user-images.githubusercontent.com/23343800/52540314-77c96400-2d88-11e9-9b1b-c39c16560781.png)

What about reducing the parameter buffer size?

(This game is so frustrating, but I love it <3)

**Comment by Electry** [comment]
Interesting, same thing happened with lights in NFSMW. We must be missing something then.

You're saying that lowering the res. doesn't help? Even when you go down to something like 640x384?
Parameter buffer size could only be a problem if it was too low.

**Comment by Doredialilligan** [comment]
The game only allows to patch the heigh, if i put 640x384 in config.txt the game set the resolution to 960x384 :(

**Comment by Electry** [comment]
what do you have in your patchlist.txt for that game?

**Comment by Doredialilligan** [comment]
```
#Blue Reflection: Maboroshi ni Mau Shojo no Ken [JP 1.05]
[PCSG00987,eboot.bin,0xB2361C99]
@IB
0:0x2F8B72 t2_mov(0,0,<ib_w>)
0:0x317172 t2_mov(0,0,<ib_h>)
@MSAA
0:0x71DFD8 uint32(<msaa>)
```

**Comment by Electry** [comment]
It should be 0x31716C instead of 0x2F8B72.

**Comment by Doredialilligan** [comment]
My bad! I don't really know where that offset come from '-.- 

At 640x384 the effects still flicker.
At 736x442 they flicker too.
