### ISSUE TITLE
[BUG] Soul Sacrifice Delta - misaligned blur

### ISSUE THREAD

**Issue by Electry** [Electry/VitaGrafixPatchlist#2]
When playing at anything other than (the default) 720x408, the blur effect becomes displaced.

![2z2x9hp](https://user-images.githubusercontent.com/12598379/50408059-7518ac80-07e4-11e9-8a87-ee95cbc4496b.jpg)

**Comment by Electry** [comment]
This happens because depth buffer stride sample size is at 960x544 set to 1920 (2x960), but for 720x408 it's 1472 (2x736), as it has to be divisible by 32. I believe something down the line still thinks it is larger than 1920 (perhaps 1962) and it gets fucked. Interestingly, if I artificially set the stride to 1984 it is still displaced but this time to the other side.

I have 0 experience with 3D or game development so I might just be throwing non-sense words around.

**Comment by Electry** [comment]
I was correct!

A few (new) shaders have hardcoded depth texture size ratio to 0.978261/0.980769 which agrees with my 720/736 vs 960/960 theory.

After patching those as well it's now positioned correctly :)

![2019-06-18-153326](https://user-images.githubusercontent.com/12598379/59688839-cd05fe00-91de-11e9-86fe-f6fe6c8fbe65.png)

**Comment by Doredialilligan** [comment]
> I was correct!
> 
> A few (new) shaders have hardcoded depth texture size ratio to 0.978261/0.980769 which agrees with my 720/736 vs 960/960 theory.
> 
> After patching those as well it's now positioned correctly :)
> 
> ![2019-06-18-153326](https://user-images.githubusercontent.com/12598379/59688839-cd05fe00-91de-11e9-86fe-f6fe6c8fbe65.png)

I'm glad to see that Vitagrafix is not dead after months without updates. Thank you so much @Electry <3

**Comment by TheMostEve** [comment]
> After patching those as well it's now positioned correctly

where is the download for new patch for this?

**Comment by Electry** [comment]
Nowhere yet, I need to update the plugin first. Right now, it can't read floats from patchlist.txt, nor do floating point math.

I could hardcode the values for 960x544, but meh, I plan on rewriting the patchlist parser anyway.

**Comment by Sprucuis** [comment]
Hi, sorry if this looks annoying, I just wanted to know, how I can fix the blur in this game? It's looks a little weird, everytime when i see this. As I understand it, for this I need to enter a floating value, but current version of plugin can't do it. 
Possible to make a Hotfix for this game?
Thank you very much. :)

P.S. Sorry for my English, this is my second language.

**Comment by Electry** [comment]
Here, try this.

[VitaGrafix.zip](https://github.com/Electry/VitaGrafixPatchlist/files/3800902/VitaGrafix.zip)
[patchlist.txt](https://github.com/Electry/VitaGrafixPatchlist/files/3800904/patchlist.txt)

**Comment by Sprucuis** [comment]
YES THAT'S WORK!!! Thanks a lot my friend! You are AMAZING!

**Comment by Electry** [comment]
Fixed in https://github.com/Electry/VitaGrafixPatchlist/commit/0c8dcbef1306c9bfc644dee760b778d5ab842250
