### ISSUE TITLE
[Request] Uncharted Golden Abyss PCSF00001 

### ISSUE THREAD

**Issue by Wontell** [Electry/VitaGrafixPatchlist#20]
Hi,
Please add  Uncharted Golden Abyss PCSF00001 to patchlist.txt

Thanks

**Comment by EnekoT2001** [comment]
You could search in vitagrafix the progress on this game, right now we can't find how to change the res/fps cap without breaking graphics/effects, I hope this gets solved but for now we can just wait and hope for the best :c

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/14fe4e0064bc9e538496f44c2e24ecb6131be450
