### ISSUE TITLE
Usage of uint32

### ISSUE THREAD

**Issue by Doredialilligan** [Electry/VitaGrafixPatchlist#25]
I've been trying to do an Atelier Sophie US 1.01 patch based on the Asia one, but I don't know how to use the uint32 parameter. Anyone can help me?

**Comment by Electry** [comment]
Did you figure it out?

**Comment by Doredialilligan** [comment]
@Electry More or less. I downloaded the Asia version of the game and searched the offset. Then, I searched for the same tipe of instruction in my US eboot.bin and it worked.

I don't really know if that parameter is always the same for all games that use it, but at least it worked in this case :)
