### ISSUE TITLE
[Request] Fate extella

### ISSUE THREAD

**Issue by rika09** [Electry/VitaGrafixPatchlist#28]
Anyone tried changing resolution in this one?

**Comment by Shinriji** [comment]
There is a patch for the asia version of vanilla Fate Extella (not the Link version), so you can try if it works for you. (Credits for that amazing tieba user that is finding a lot of offsets for vita games) 

# Fate/EXTELLA [ASIA 1.01]
[PCSH00299,eboot.bin]
@IB
0:0x4ED268 t2_mov(0,0,<ib_w>)
0:0x4ED26E t2_mov(0,0,<ib_h>)

**Comment by rika09** [comment]
Ah forgot to mention looking for US version.

**Comment by Electry** [comment]
Here you go

```
# Fate/EXTELLA: The Umbral Star [US 1.01]
[PCSE00928,eboot.bin,0xEF934DB7]
# Fate/EXTELLA [ASIA 1.01]
[PCSH00299,eboot.bin,0x4E5BE9F4]
@IB
0:0x4ED268 t2_mov(0,0,<ib_w>)
0:0x4ED26E t2_mov(0,0,<ib_h>)
```

**Comment by rika09** [comment]
No adress for us?

**Comment by Electry** [comment]
It's right there, same as asia.

**Comment by rika09** [comment]
Tried it with few free missions and seems everything working fine without any glitches. Thanks.

**Comment by Electry** [comment]
added to patchlist.txt
