### ISSUE TITLE
[BUG] Zero Time Dilemma (PCSE00781)

### ISSUE THREAD

**Issue by Shinriji** [Electry/VitaGrafixPatchlist#29]
I found a patch elsewhere for enabling a FPS cap on Zero Time Dilemma, and I did some testing looking for merging with the official patchlist in the future, since I have this game. 

# Zero Escape: Zero Time Dilemma [US 1.01]
[PCSE00781,eboot.bin,0xA80A9ECE]
`@FPS`
`0:0x2C4E t1_mov(0,<vblank>)`
`0:0x2C58 t1_mov(0,<vblank>)`

The author said that it works, but I get a VG OSD message "config file info is incorrect" (or something like that) that keeps appearing from time to time, even if I don't change the FPS on the config file. 
The only solution is to remove entirely the patch from the patchlist. Any help?

PS - ZTD is one of the games that crashes when using 500mhz OC, but I don't know if is related to that.

**Comment by Electry** [comment]
It looks okay as far as syntax goes.

Could you check log.txt (and copy it here if possible)? There should be more info.

**Comment by Shinriji** [comment]
https://imgur.com/a/qPXqOMm

**Comment by Electry** [comment]
Well there you go. line 952 in config.txt contains invalid option. If it's MSAA make sure you have v4.0 and not the previous alpha builds.

**Comment by Shinriji** [comment]
I fixed the config issue, but the patch definetly don't work. Framerate is unlocked and is all over the place, and even on 500mhz it keeps fluctuating at 35-45FPS that causes weird framepace issues. I was hoping that a 30FPS lock could solve the issue, but...

And since I already beat the game (and unfortunately isn't that good), I'm closing this issue.
