### ISSUE TITLE
Ys VIII - Lacrimosa of Dana 60 fps patch

### ISSUE THREAD

**Issue by Doredialilligan** [Electry/VitaGrafixPatchlist#33]
Here you have the fps patch for the US 1.02 game:

```
config.txt
[PCSE01103]
FPS=60

patchlist.txt
#Ys VIII - Lacrimosa of Dana [US 1.02]
[PCSE01103,eboot.bin]
@FPS
0:0x289622 nop() *2
```
Edit: I just noticed that the menus are double speed, like in Project Diva games.

**Comment by TheMostEve** [comment]
Not work still 30 fps

**Comment by Doredialilligan** [comment]
The patch works for me. It unlocks the 30 fps cap that the game has. It don't give you stable 60 fps, but cinematics jump up to 40-45 fps and the rest of the game jumps into 35 fps. Check your config.txt and your patchlist.txt, also check your game region and your game update. If the menus are double speed, the patch is working.

**Comment by Caliburnflash** [comment]
Does this work on jp version?

**Comment by Doredialilligan** [comment]
I haven't got the JP version, but surely it wont work :(

**Comment by Caliburnflash** [comment]
I tried it on us version, works well.

**Comment by Doredialilligan** [comment]
That's good, but with my patch the menus are double speed. I'm missing something, but I don't know how to resolve the problem.

It's better to use VGi Allow 1 mode. It unlocks the framerate and the menus are normal speed :)

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/265eac85f2d065e42e8056c4981fba05ab6e468b
