### ISSUE TITLE
[Request] Injustice

### ISSUE THREAD

**Issue by eddyfire** [Electry/VitaGrafixPatchlist#34]
Anyone think they could change the reso for Injustice? Been hoping for this game for awhile... It looks really bad right now... 😥

**Comment by Electry** [comment]
![2019-02-11-214208](https://user-images.githubusercontent.com/12598379/52592405-95f59980-2e46-11e9-9648-544415cae8b4.png)

Here the healthbars disappear completely xD

**Comment by SheidCraft** [comment]
@Electry Wow, and there is no possibility to add to the patchlist for possible improvement in the future

**Comment by nad45** [comment]
Cool 
And how does it run?
Could you share the patchlist values? (If possible EU version)

**Comment by eddyfire** [comment]
Wow, thanks..but it does looks good...yeah u mind sharing? maybe we could give it a try..

**Comment by nad45** [comment]
I downloaded the screenshot in my Vita.
It looks very good at native resolution.

**Comment by nad45** [comment]
Hi @Electry 
Hi
Could you give us the Patchlist infos for Injustice please?
Even without lifebars, i would like to try

**Comment by eddyfire** [comment]
Yeah @Electry .... Cant wait test it out..

**Comment by Electry** [comment]
Added in https://github.com/Electry/VitaGrafixPatchlist/commit/61240270d2978561fabcc6e0ee0f896702ce1e03
