### ISSUE TITLE
No Resolution Change Option in Fate Extella

### ISSUE THREAD

**Issue by KazutoPH** [Electry/VitaGrafixPatchlist#35]
![2019-02-11-185029](https://user-images.githubusercontent.com/43802163/52558886-b87bb880-2e2e-11e9-8146-7f8809a962ad.png)

**Comment by Electry** [comment]
@Kirezar
could it be because US/ASIA are grouped together?
```
# Fate/EXTELLA: The Umbral Star [US 1.01]
[PCSE00928,eboot.bin,0xEF934DB7]
# Fate/EXTELLA [ASIA 1.01]
[PCSH00299,eboot.bin,0x4E5BE9F4]
@IB
0:0x4ED268 t2_mov(0,0,<ib_w>)
0:0x4ED26E t2_mov(0,0,<ib_h>)
```

**Comment by Kirezar** [comment]
Yeah, I originally had that problem on games like the Ratchet and Clank, that had different titles for different regions, but I grouped them together on purpose. I need to check it to see if there's something missing there.

It seems to be grouping them fine which is what I wanted, but not displaying the option. I'll take a look into it later today, thanks for pinging me.

**Comment by Kirezar** [comment]
Ok fixed it, was a problem on how I was dealing with the grouping of the game.

here if you wanna try it and see if everything's okay with the grouping @KazutoPH 

[VitaGrafixConfigurator.zip](https://github.com/Electry/VitaGrafixPatchlist/files/2853711/VitaGrafixConfigurator.zip)

**Comment by KazutoPH** [comment]
It works thank you very much :D
