### ISSUE TITLE
Atelier Sophie gets syntax error & Atelier Lydie (C2-12828-1) - (SOLVED)

### ISSUE THREAD

**Issue by gasaiyuno0112** [Electry/VitaGrafixPatchlist#36]
Atelier Sophie gets Syntax error : 
[CONFIG] Parsing config.txt
[CONFIG] Found [MAIN] section, pos=0
[CONFIG] Found [PCSE00892] section, pos=116
[PATCH] Parsing patchlist.txt
[MAIN] Patching seg000 : 00358E70 to 5F F4 70 71, size=4
[MAIN] Patching seg000 : 00358E7C to 5F F4 08 72, size=4
[MAIN] Patching seg000 : 00358E94 to 5F F4 70 71, size=4
[MAIN] Patching seg000 : 00358E98 to 5F F4 08 72, size=4
[MAIN] Patching seg000 : 00354BDC to 5F F4 70 73, size=4
[MAIN] Patching seg000 : 000B61DC to 5F F4 08 71, size=4
[PATCH] ERROR: Syntax error: invalid address
[IO] ERROR: Failed to parse line 1516, pos=493, end=513
[PATCH] 181 total patches found in patchlist.txt
![2019-02-12-101748](https://user-images.githubusercontent.com/47547102/52607466-3da7b180-2eb1-11e9-9fd1-a6458f57b412.png)

Ans Atelier Lydie gets error (C2-12828-1)
![2019-02-12-102746](https://user-images.githubusercontent.com/47547102/52607505-5912bc80-2eb1-11e9-8c53-c6b20653053e.png)

INTERNAL RESOLUTION : 960X544

**Comment by Doredialilligan** [comment]
```
#Atelier Sophie: The Alchemist of the Mysterious Book [US 1.01]
[PCSE00892,eboot.bin]
@IB
0:0x358E70 t2_mov(1,1,<ib_w>)
0:0x358E7C t2_mov(1,2,<ib_h>)
0:0x358E94 t2_mov(1,1,<ib_w>)
0:0x358E98 t2_mov(1,2,<ib_h>)
0:0x354BDC t2_mov(1,3,<ib_w>)
0:0xB61DC t2_mov(1,1,<ib_h>)
1:0xB3704 uint(<ib_h>)

#Atelier Lydie & Suelle: Fushigi na Kaiga no Renkinjutsushi [JP 1.06]
[PCSG01116,eboot.bin]
@IB
0:0x32FBF4 t2_mov(1,0,<ib_w>)
0:0x32FBFA t2_mov(1,0,<ib_h>)

#Atelier Sophie: The Alchemist of the Mysterious Book [US 1.01]
[PCSE00892,eboot.bin]
@IB
0:0x358E70 t2_mov(1,1,<ib_w>)
0:0x358E7C t2_mov(1,2,<ib_h>)
0:0x358E94 t2_mov(1,1,<ib_w>)
0:0x358E98 t2_mov(1,2,<ib_h>)
0:0x354BDC t2_mov(1,3,<ib_w>)
0:0xB61DC t2_mov(1,1,<ib_h>)
1:0xB3704 uint(<ib_h>)

#Atelier Lydie & Suelle: Fushigi na Kaiga no Renkinjutsushi [JP 1.06]
[PCSG01116,eboot.bin]
@IB
0:0x32FBF4 t2_mov(1,0,<ib_w>)
0:0x32FBFA t2_mov(1,0,<ib_h>)

#Blue Reflection: Maboroshi ni Mau Shojo no Ken [JP 1.05]
[PCSG00987,eboot.bin]
@IB
0:0x31716C t2_mov(1,0,<ib_w>)
0:0x317172 t2_mov(1,0,<ib_h>)
@MSAA
0:0x71DFD8 uint32(<msaa>)
```
Here you have all the errors corrected. I'm going to do a new pull request right now :)

**Comment by gasaiyuno0112** [comment]
![2019-02-12-184937](https://user-images.githubusercontent.com/47547102/52630479-563aba80-2ef7-11e9-83a1-fe20e2c51378.png)
![2019-02-12-184952](https://user-images.githubusercontent.com/47547102/52630481-563aba80-2ef7-11e9-8d4e-543cdb35148e.png)
im still getting syntax error in atelier sophie i dont know why i already copy them line by line too

and Thank You for Atelier Lydie its already working thanks :)

**Comment by Doredialilligan** [comment]
```
#Atelier Sophie: The Alchemist of the Mysterious Book [US 1.01]
[PCSE00892,eboot.bin]
@IB
0:0x358E70 t2_mov(1,1,<ib_w>)
0:0x358E7C t2_mov(1,2,<ib_h>)
0:0x358E94 t2_mov(1,1,<ib_w>)
0:0x358E98 t2_mov(1,2,<ib_h>)
0:0x354BDC t2_mov(1,3,<ib_w>)
0:0xB61DC t2_mov(1,1,<ib_h>)
1:0xB3704 uint(<ib_h>)
```
I'm so sorry for all the inconveniences. It will work now :)

**Comment by gasaiyuno0112** [comment]
wow its working now, im really grateful Thanks :D
