### ISSUE TITLE
Mortal Kombat PCSE00023

### ISSUE THREAD

**Issue by SheidCraft** [Electry/VitaGrafixPatchlist#39]
![2019-02-16-192238](https://user-images.githubusercontent.com/42513747/52902502-8f8a6780-3222-11e9-9755-ceece31c01d7.png)
![2019-02-16-192454](https://user-images.githubusercontent.com/42513747/52903987-97ec9d80-3236-11e9-9928-49ff86a313f7.png)
![2019-02-16-192523](https://user-images.githubusercontent.com/42513747/52903988-98853400-3236-11e9-957f-dfcdd7bda254.png)
![2019-02-16-192320](https://user-images.githubusercontent.com/42513747/52903989-98853400-3236-11e9-8815-f4eb841c33db.png)

```
[PCSE00023,eboot.bin,0xAB5E7564]
@FB
0:0x2424BE t2_mov(0,0,<fb_w>)
0:0x2424C2 t2_mov(0,1,<fb_h>)
0:0x2055F8 t2_mov(0,2,</,<,<fb_w>,<fb_w>>,640>)
0:0x205600 t2_mov(0,3,</,<,<fb_h>,<fb_h>>,368>)
```

**Comment by nad45** [comment]
Hi
Did you solve the UI problem?

**Comment by diegorocha2007** [comment]
Looks great. You managed to fix the HUD. Thanks a lot!
But I tried to add it to the list and it gives me an error: "Patchfile is invalid or contains sintax error!"
Do you know what may be causing it? It only happens in MK.

**Comment by SheidCraft** [comment]
@diegorocha2007 This improvement was released by @Electry itself, albeit under the European version.
https://github.com/Electry/VitaGrafix/issues/143#issuecomment-464273538

**Comment by Electry** [comment]
just FYI, it breaks all sprite-based effects (including blood, fire, smoke, etc...)
and it says invalid patchfile because OP didn't put it inside `code tag`.

**Comment by SheidCraft** [comment]
@Electry
this is seen in the third picture near Smoke. Is it possible to turn off effects at all? Leaving only blood, I did not see any problems with it.

**Comment by diegorocha2007** [comment]
Oh, I see. In that case, thank you @Electry
As I didn't managed to make it work myself, I'll wait until it's merged in the official Patchlist.
Keep up the good work!

**Comment by Feardarks** [comment]
3rd image is best. what is settings ?

**Comment by nahob** [comment]
which file should i paste this text into. pls help

**Comment by Sal-gamer** [comment]
Conseguiu deixar 100%?

**Comment by Electry** [comment]
US region added in https://github.com/Electry/VitaGrafixPatchlist/commit/b35ff59f3648c264f3d7c1317a1e76a03fb8a2a1
