### ISSUE TITLE
Crashes in US Trails of Cold Steel [Includes Fixes]

### ISSUE THREAD

**Issue by mcallbosco** [Electry/VitaGrafixPatchlist#4]
Sorry about bothering you again but with this version of the plugin, it crashed TOCS while other games I tried worked fine.

It seems like the Japanese and Asian versions have the same id listed in the patchlist.txt file.

Looking through the txt files with all the patches, I also noticed the US version is listed as 1.01 while it should be 1.02.

The JP one should have "PCSG00195" and the ASIA one should have "PCSH00074"

There was also a crash issue I found the fix for.
I also noticed that the bottom Hex values seem to only have a 2 value difference from each other, while the other ones have a 4 value difference. 

Changing the US version to have the 4 value difference seemed to fix it from crashing while going past the splash screens.

I'm not exactly confident in my git skills so sorry if there was a way to push a edit with all of this for you to approve or something. Thank you for making this amazing plugin and making it even better with this update.

**Comment by mcallbosco** [comment]
I might as well mention testing the patch it seems like the blur is still a bit off by a pixel or two. But then when I increment the decimal up it doesn't change except when I go to 10250 or over it still ends up not onto the object properly this time overlapping on the other side.

I know its probably not a issue you can fix with a value replacement but I just wanted to have this pointed out incase anyone else notices it.

**Comment by Electry** [comment]
Yeaaaaah, I didn't really know what else to do with that.

You might as well try replacing the t2_mov with t3_mov on that one line, as the former is less precise (can only set the value to either 980 or then 984). You'd also have to remove the leading "1," as T3 only takes 2 parameters, so "t3_mov(2,</,<*,<ib_w>,10222>,10000>)" and then try with 10222 or 10230.
