### ISSUE TITLE
Some game patches

### ISSUE THREAD

**Issue by q6164007** [Electry/VitaGrafixPatchlist#43]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Gundam SEED Battle Destiny | Artdink | 960x544 | 704x384 | 4x | 30
```
# Gundam SEED Battle Destiny [JP 1.01]
[PCSG00040,eboot.bin,0x657F506B]
@IB
0:0x7761EC uint32(<ib_w>)
0:0x7761F0 uint32(<ib_h>)
@FPS
0:0x72189C a1_mov(0,0,<vblank>)
```

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
J-Stars Victory Vs+ | Bandai Namco | 960x544 | 768x448 | none | 30
```
# J-Stars Victory Vs+ [ASIA 1.00]
[PCSH00136,eboot.bin,0x86EAD93B]
@IB
0:0x2BD01E t2_mov(1,4,0xF00000) 
0:0x2BCF62 t2_mov(1,14,0x6100000) 
1:0x485F8 uint32(<ib_w>)
1:0x485FC uint32(<ib_h>)
# J-Stars Victory Vs+ [US 1.02]
[PCSE00595,eboot.bin,0x60650340]
@IB
0:0x2BCEDE t2_mov(1,4,0xF00000) 
0:0x2BCE22 t2_mov(1,14,0x6100000) 
1:0x485F8 uint32(<ib_w>)
1:0x485FC uint32(<ib_h>)
# J-Stars Victory Vs+ [EU 1.00]
[PCSB00713,eboot.bin,0x52574668]
@IB
0:0x2BD12A t2_mov(1,4,0xF00000) 
0:0x2BD06E t2_mov(1,14,0x6100000) 
1:0x485F8 uint32(<ib_w>)
1:0x485FC uint32(<ib_h>)
# J-Stars Victory Vs [JP 1.02]
[PCSG00300,eboot.bin,0xA11C13E2]
@IB
0:0x28D338 t2_mov(1,5,0xD00000)
0:0x28D286 t2_mov(1,12,0x6300000)
1:0x27FBC uint32(<ib_w>)
1:0x27FC0 uint32(<ib_h>)
```

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Catherine: Full Body | Atlus | 960x544 | 720x408 | none | 30
# Catherine: Full Body [JP 1.03]
[PCSG01179,eboot.bin,0x193F08A5]
@IB
0:0xBBE98 t2_mov(1,5,<ib_w>)
0:0xBBEA0 t2_mov(1,6,<ib_h>)
0:0x345E6A t2_mov(1,14,<ib_w>)
0:0x345E6E t2_mov(1,12,<ib_h>)

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Catherine: Full Body | Atlus | 960x544 | 720x408 | none | 30
```
# Catherine: Full Body [JP 1.03]
[PCSG01179,eboot.bin,0x193F08A5]
@IB
0:0xBBE98 t2_mov(1,5,<ib_w>)
0:0xBBEA0 t2_mov(1,6,<ib_h>)
0:0x345E6A t2_mov(1,14,<ib_w>)
0:0x345E6E t2_mov(1,12,<ib_h>)

```

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Street Fighter X Tekken | Capcom | 960x544 | 640x480 | 4x | 60
```
# Street Fighter X Tekken [US 1.08]
[PCSE00005,eboot.bin,0xEA3CB3D]
@IB
0:0x94D240 t2_mov(1,5,<ib_w>)
0:0x94D244 t2_mov(1,2,<ib_h>)
# Street Fighter X Tekken [EU 1.08]
[PCSB00144,eboot.bin,0x4C4DB951]
@IB
0:0x94D298 t2_mov(1,5,<ib_w>)
0:0x94D29C t2_mov(1,2,<ib_h>)
# Street Fighter X Tekken [JP 1.08]
[PCSG00063,eboot.bin,0xAAE7FEDF]
@IB
0:0x94D28C t2_mov(1,5,<ib_w>)
0:0x94D290 t2_mov(1,2,<ib_h>)
```

**Comment by nad45** [comment]
Thanks

**Comment by diegorocha2007** [comment]
Thank you very much!

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Supremacy MMA Unrestricted | Kung Fu Factory | 960x544 | 720x408 | 4x | 60

```
# Supremacy MMA: Unrestricted [US 1.00]
[PCSE00012,eboot.bin,0x860FE0A7]
@IB
0:0x58EBA t2_mov(1,1,<ib_w>)
0:0x58EBE t2_mov(1,2,<ib_h>)
```

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Macross Delta Scramble | Bandai Namco | 960x544 | 800x448 | 2x | 30

```
# Macross Delta Scramble [JP 1.02]
[PCSG00947,eboot.bin]
@IB
0:0x7B6AB0 a1_mov(0,0,<ib_w>)
0:0x7B6AB8 a1_mov(0,0,<ib_h>)
0:0x7AC3FC a1_mov(0,0,<ib_w>)
0:0x7AC404 a1_mov(0,1,<ib_h>)
0:0x7AA920 a1_mov(0,0,<ib_w>)
0:0x7AA928 a1_mov(0,1,<ib_h>)
0:0x7AAC88 a1_mov(0,2,<ib_w>)
0:0x7AAC90 a1_mov(0,3,<ib_h>)
0:0x7AB4F8 a1_mov(0,3,<ib_w>)
0:0x7AB500 a1_mov(0,5,<ib_h>)
```

**Comment by Feardarks** [comment]
thhaankkssss <3

**Comment by nad45** [comment]
Thanks
Regarding Macross, is it possible to have MSAA 4x?

**Comment by q6164007** [comment]
> Thanks
> Regarding Macross, is it possible to have MSAA 4x?

Sorry, I have no idea. Maybe @Electry  can do it.

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Tokyo   Xanadu | Nihon Falcom | 960x544 | 720x408 | 2x | 30

I pixel-counted gameplay screenshot and it's 720x408,but it was scaled to 960x544 output, so changing it to 1280x720 is the real 960x544.Setting MSAA=4 does not affect the number of frames.
The best setting is IB=1280x720  MSAA=4
```
# Tokyo Xanadu [JP 1.04]
[PCSG00608,eboot.bin,0x95ACFA1D]
@IB
0:0xE75C8 t2_mov(1,1,<ib_w>)
0:0xE75CC t2_mov(1,2,<ib_h>)
0:0xE7602 t2_mov(1,1,<ib_w>)
0:0xE7606 t2_mov(1,2,<ib_h>)
@MSAA
0:0xE7594 t1_mov(4,<*,<msaa>,2>)
# Tokyo Xanadu [ASIA 1.00]
[PCSH10009,eboot.bin,0x2BE0554C]
@IB
0:0xE7A48 t2_mov(1,1,<ib_w>)
0:0xE7A4C t2_mov(1,2,<ib_h>)
0:0xE7A82 t2_mov(1,1,<ib_w>)
0:0xE7A86 t2_mov(1,2,<ib_h>)
@MSAA
0:0xE7A14 t1_mov(4,<*,<msaa>,2>)
# Tokyo Xanadu [US 1.00]
[PCSE00893,eboot.bin,0x9420F248]
@IB
0:0xE7730 t2_mov(1,1,<ib_w>)
0:0xE7734 t2_mov(1,2,<ib_h>)
0:0xE776A t2_mov(1,1,<ib_w>)
0:0xE776E t2_mov(1,2,<ib_h>)
@MSAA
0:0xE76FC t1_mov(4,<*,<msaa>,2>)
# Tokyo Xanadu [EU 1.00]
[PCSB01062,eboot.bin,0x061171E4]
@IB
0:0xE7818 t2_mov(1,1,<ib_w>)
0:0xE781C t2_mov(1,2,<ib_h>)
0:0xE7852 t2_mov(1,1,<ib_w>)
0:0xE7856 t2_mov(1,2,<ib_h>)
@MSAA
0:0xE77E4 t1_mov(4,<*,<msaa>,2>)
```

**Comment by diegorocha2007** [comment]
On the previous Catherine patch I was using, for JP 1.01, it was possible to set the IB to 1280x720. Yours however, crashed the game when trying this resolution. Do you know if it's a limitation of 1.03 for this kind of patch?

**Comment by q6164007** [comment]
@diegorocha2007 Of course, I am the original author of the 1.01 patch. To set it to 1280x720, it needs more 8mb free VRAM, I don't know what the bad consequences will be, I don't recommend it.If you need to set it to 1280x720, you can use this patch. I am very curious, European and American players will like Japanese games?
```
# Catherine: Full Body [JP 1.03]
[PCSG01179,eboot.bin,0x193F08A5]
@IB
0:0xBBE98 t2_mov(1,5,<ib_w>)
0:0xBBEA0 t2_mov(1,6,<ib_h>)
0:0x345E6A t2_mov(1,14,<ib_w>)
0:0x345E6E t2_mov(1,12,<ib_h>)
0:0x345D38 t2_mov(1,1,<if_gt,<*,<ib_w>,<ib_h>>,<*,960,544>,0x800000,0x1000000>)
```

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Ys VIII: Lacrimosa of Dana | Nihon Falcom | 960x544 | 960x512 840x476 720x320 | none | 30

```
# Ys VIII: Lacrimosa of Dana [EU 1.02]
[PCSB01128,eboot.bin,0x804268F1]
# Ys VIII: Lacrimosa of Dana [US 1.02]
[PCSE01103,eboot.bin,0x804268F1]
@IB
0:0x18A1E2 t2_mov(0,4,<ib_w>)
0:0x18A1E6 t2_mov(0,5,<ib_h>)
0:0x18A1F0 t2_mov(0,6,<ib_w>)
0:0x18A1F4 t2_mov(0,7,<ib_h>)
0:0x18A1FA t2_mov(1,4,<ib_w>)
0:0x18A202 t2_mov(1,5,<ib_h>)
0:0x191798 t2_mov(1,0,<ib_w>)
0:0x1917A6 t2_mov(1,0,<ib_h>)
0:0x19187A t2_mov(1,1,<ib_w>)
0:0x191888 t2_mov(1,1,<ib_h>)
@FPS
0:0x289620 t1_mov(0,<vblank>)
# Ys VIII: Lacrimosa of Dana [JP 1.02]
[PCSG00881,eboot.bin,0xC2D25375]
@IB
0:0x188F22 t2_mov(0,4,<ib_w>)
0:0x188F26 t2_mov(0,5,<ib_h>)
0:0x188F30 t2_mov(0,6,<ib_w>)
0:0x188F34 t2_mov(0,7,<ib_h>)
0:0x188F3A t2_mov(1,4,<ib_w>)
0:0x188F42 t2_mov(1,5,<ib_h>)
0:0x190574 t2_mov(1,0,<ib_w>)
0:0x190582 t2_mov(1,0,<ib_h>)
0:0x190656 t2_mov(1,1,<ib_w>)
0:0x190664 t2_mov(1,1,<ib_h>)
@FPS
0:0x285FD0 t1_mov(0,<vblank>)
# Ys VIII: Lacrimosa of Dana [ASIA 1.02]
[PCSH00297,eboot.bin,0xB4F97187]
@IB
0:0x189130 t2_mov(0,4,<ib_w>)
0:0x189134 t2_mov(0,5,<ib_h>)
0:0x18913E t2_mov(0,6,<ib_w>)
0:0x189142 t2_mov(0,7,<ib_h>)
0:0x189148 t2_mov(1,4,<ib_w>)
0:0x189150 t2_mov(1,5,<ib_h>)
0:0x1906CA t2_mov(1,0,<ib_w>)
0:0x1906D8 t2_mov(1,0,<ib_h>)
0:0x1907AC t2_mov(1,1,<ib_w>)
0:0x1907BA t2_mov(1,1,<ib_h>)
@FPS
0:0x285834 t1_mov(0,<vblank>)
```

**Comment by diegorocha2007** [comment]
@q6164007 oh, I didn't know you were the original author, I'm talking to the right person then. You're on fire lately, all that awesome patches, the community thanks you (and me too)!
Well, I'll try this new patch, if it needs more VRAM, maybe the consequences could be crashes later in the game perhaps? 720p downscaled looks too good to be ignored, haha.
Answering your question, I can't really tell about them, but being a brazilian myself, we are very into japanese games over here. And Catherine is like, Vita's last AAA, this means a lot.

**Comment by Doredialilligan** [comment]
Your work for this comunity is just amazing. Thank you so much for everything that you have done and for the future releases you will make. 
Are you interested or working on Nights of Azure I & II or the rest of the MSAA patches for Atelier games? :)

**Comment by q6164007** [comment]
@Doredialilligan We should thank Electry for his great work and tutorials. If I had free time, I would try those games. But I still have a lot of game patches to deal with, so maybe it will take a while.

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
The Legend of Heroes: Trails of Cold Steel II | Nihon Falcom | 960x544 | 720x408 | 2x | 30

Add MSAA patches to official patchlist.
```
# The Legend of Heroes: Trails of Cold Steel II [EU 1.00]
[PCSB01016,eboot.bin,0xBEE60BC5]
@MSAA
0:0x1399DE t1_mov(1,<*,<msaa>,2>)
0:0x139986 t1_mov(1,<*,<msaa>,2>)
# The Legend of Heroes: Trails of Cold Steel II [US 1.01]
[PCSE00896,eboot.bin,0x56DB15C5]
@MSAA
0:0x1398F6 t1_mov(1,<*,<msaa>,2>)
0:0x13989E t1_mov(1,<*,<msaa>,2>)
# The Legend of Heroes: Trails of Cold Steel II [JP 1.03]
[PCSG00354,eboot.bin,0x2998B4C3]
@MSAA
0:0x1393C0 t1_mov(1,<*,<msaa>,2>)
0:0x139414 t1_mov(1,<*,<msaa>,2>)
# The Legend of Heroes: Trails of Cold Steel II [ASIA 1.03]
[PCSH00075,eboot.bin,0xF1242A81]
@MSAA
0:0x1399E2 t1_mov(1,<*,<msaa>,2>)
0:0x139A3A t1_mov(1,<*,<msaa>,2>)
```

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Summon Night 6:Lost Borders | Media.Vision | 960x544 | 960X544 | 2x | 30

Runs well at 4x msaa.
```
# Summon Night 6:Lost Borders [EU 1.00]
[PCSB01013,eboot.bin,0x243B98A5]
# Summon Night 6:Lost Borders [US 1.00]
[PCSE00951,eboot.bin,0x88F34BB1]
@MSAA
0:0x2C0308 t1_mov(4,<msaa>)
# Summon Night 6:Lost Borders [JP 1.03]
[PCSG00827,eboot.bin,0x3CD87445]
@MSAA
0:0x2BFA18 t1_mov(4,<msaa>)
# Summon Night 6:Lost Borders [ASIA 1.03]
[PCSH00225,eboot.bin,0x919479D7]
@MSAA
0:0x2BF9C8 t1_mov(4,<msaa>)
```

**Comment by Errol1886** [comment]
@q6164007 Do you have a code that will make the frame rate in the game "Resogun" 60 FPS or double speed?

**Comment by q6164007** [comment]
2x speed
```
# RESOGUN [JP 1.00]
[PCSC00088,eboot.bin,0x9C16CEBD]
@FB
0:0x165A08 t2_mov(1,0,<fb_w>)
0:0x165A0E t2_mov(1,0,<fb_h>)
@FPS
0:0x1398F6 t1_mov(0,<vblank>)
# RESOGUN [US 1.01]
[PCSA00103,eboot.bin,0x871F1F8C]
@FB
0:0x165A28 t2_mov(1,0,<fb_w>)
0:0x165A2E t2_mov(1,0,<fb_h>)
@FPS
0:0x139916 t1_mov(0,<vblank>)
# RESOGUN [EU 1.01]
[PCSF00262,eboot.bin,0x67CD2E83]
@FB
0:0x165AC4 t2_mov(1,0,<fb_w>)
0:0x165ACA t2_mov(1,0,<fb_h>)
@FPS
0:0x1399B2 t1_mov(0,<vblank>)
```

**Comment by Errol1886** [comment]
@q6164007 You are the man. Thank you for all your hard work. People like myself really do appreciate what you have done for the PS Vita community.

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Spy Hunter | TT Fusion | 640x368 | 640x368 | 4x | 30

BUG:The game start interface is not fully displayed, but does not affect you play.
```
# Spy Hunter [EU 1.00]
[PCSB00166,eboot.bin,0x4D752CEE]
@FB
0:0xE9A00 t2_mov(1,1,0xD00000)
0:0xD1638 t2_mov(1,3,<fb_w>)
0:0xD163E t2_mov(1,2,<fb_h>)
@FPS
0:0xE921E t1_mov(0,<vblank>)
@MSAA
0:0xD1644 t1_mov(4,<*,<msaa>,2>)
# Spy Hunter [US 1.00]
[PCSE00068,eboot.bin,0x9BB899D3]
@FB
0:0xE99BC t2_mov(1,1,0xD00000)
0:0xD15F4 t2_mov(1,3,<fb_w>)
0:0xD15FA t2_mov(1,2,<fb_h>)
@FPS
0:0xE91DA t1_mov(0,<vblank>)
@MSAA
0:0xD1600 t1_mov(4,<*,<msaa>,2>)
```

**Comment by nad45** [comment]
Once again, thank you !
If possible, could you take a look at Epic Mickey 2?

**Comment by Exia-Ti885** [comment]
Hello can I RQ patchlist for Digimon World : Next Order (Asia) and Toxyo Xanadu (USA)?

anyways Thank you so much! for your work!

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
Disney Epic Mickey 2: The   Power of Two | Junction Point, Blitz   Games | 960x544 | 720x408 | none | 30

```
# Disney Epic Mickey 2: The Power of Two [EU 1.00]
[PCSF00308,eboot.bin,0xE13F06A1]
@IB
0:0x106EF3C uint32(<ib_w>)
0:0x106EF40 uint32(<ib_h>)
```

**Comment by Doredialilligan** [comment]
You are so nice @q6164007 You attend most of our request and help us to enjoy more and more our PSVita. @Electry and you are the best :)

**Comment by q6164007** [comment]
@Doredialilligan I tried to upgrade other Atelier games from 2x MSAA to 4x MSAA, but it would make the game crash, I don't know why, but I am definitely not because of insufficient VRAM.

**Comment by Doredialilligan** [comment]
Could you please share the patches? Its just for documentation, because MSAA doesn´t make the games run better in the case of Atelier games.

The problem could be the RAM block or the parameter buffer, try with those :)

**Comment by nad45** [comment]
Wow, thanks a lot for Epic Mickey :)
That was fast!!

**Comment by q6164007** [comment]
@Doredialilligan I tried to increase memory and the game was still crashing. I only tested Atelier Ayesha and some KOEI TECMO games, both using the same game engine. You can quickly find the MSAA offset by searching for 0xC000000, which is usually expressed like this 0,1,2,0xC000000
```
# Atelier Ayesha Plus ~The Alchemist of Dusk~ [JP 1.02]
[PCSG00347,eboot.bin]
@MSAA
0:0x70813C uint32(<msaa>)
```

**Comment by Doredialilligan** [comment]
Ok, I will try the rest of  Atelier games :) Thank you so much!

**Comment by q6164007** [comment]
@Exia-Ti885 你是中国人？数码宝贝世界已经是原生分辨率了，帧数也没有限制，不知道你还要修改什么呢？

**Comment by Exia-Ti885** [comment]
> @Exia-Ti885 你是中国人？数码宝贝世界已经是原生分辨率了，帧数也没有限制，不知道你还要修改什么呢？

so sorry..I can't read chinese..I use google to translate your chat, you mean digimon world already run on native res? I thought it's not, thank you for let me know.

**Comment by q6164007** [comment]
Sorry, you want the Asian version, I thought you were Chinese. Yes, the game is native resolution.

**Comment by Doredialilligan** [comment]
@q6164007 I tried to change MSAA for Atelier Lydie & Suelle, but it doesn't change.
Please, take a look :)
#Atelier Lydie & Suelle: Fushigi na Kaiga no Renkinjutsushi [JP 1.06]
[PCSG01116,eboot.bin,0xFDABB61E]
@MSAA
0:0x81371C uint32(<msaa>)

**Comment by Exia-Ti885** [comment]
> Sorry, you want the Asian version, I thought you were Chinese. Yes, the game is native resolution.

I see, I want Asian version, because it have english language on it, anyways Thank You!

**Comment by q6164007** [comment]
@Doredialilligan 2x MSAA=1
```
typedef enum SceGxmMultisampleMode {
	SCE_GXM_MULTISAMPLE_NONE = 0,
	SCE_GXM_MULTISAMPLE_2X = 1,
	SCE_GXM_MULTISAMPLE_4X = 2
} SceGxmMultisampleMode;
```
```
#Atelier Lydie & Suelle: Fushigi na Kaiga no Renkinjutsushi [JP 1.06]
[PCSG01116,eboot.bin,0xFDABB61E]
@MSAA
0:0x813718 uint32(<msaa>)
```
![捕获](https://user-images.githubusercontent.com/48059442/54291286-4fcb5b80-45e7-11e9-85c3-74d15f50053b.PNG)

**Comment by Doredialilligan** [comment]
Thank you @q6164007 It chashes at 4x, but works at 1x. I suppose that you can decrease the MSAA, but not increase it :(

**Comment by greggameplayer** [comment]
@q6164007 can you make a tutorial on how to find the offsets of MSAA, Internal Frame Buffers and stuff like that ?

**Comment by Errol1886** [comment]
@q6164007 

Any native resolution codes for the following games:

- Sine Mora
- Gravity Rush
- Final Fantasy X HD Remaster
- Oddworld: New 'n' Tasty
- Uncharted: Golden Abyss
- Injustice: Gods Among Us Ultimate Edition
- Disney Infinity 2.0 Play Without Limits
- Call of Duty Black Ops Declassified
- HELLDIVERS
- Flower
- Final Horizon

**Comment by kane159** [comment]
Any chance for night trap?

**Comment by q6164007** [comment]
@Errol1886 I did a quick test. Some of these games had native resolutions and some had image failures.

- Sine Mora,Final Fantasy X HD Remaster,Oddworld: New 'n' Tasty,HELLDIVERS,Final Horizon,these are native resolutions.

- Gravity Rush and Injustice: Gods Among Us Ultimate Edition,there are some image failures.

- Uncharted and COD increase the resolution will make the game crash.

- Disney Infinity 2.0 Play Without Limits,I don't have this game.

- Flower，I can't find the resolution offset.

**Comment by q6164007** [comment]
@greggameplayer Sorry, I only use Chinese and Japanese,I can't do an English tutorial. You can use Electry's tutorial.[Electry's Blog](http://psvita.chvila.sk/guides/) and #19

**Comment by nad45** [comment]
Regarding Injustice, what is the issue?
Same as this? : https://github.com/Electry/VitaGrafixPatchlist/issues/34

**Comment by Errol1886** [comment]
@q6164007 Thanks for replying and looking into the games I suggested a patch for.

In Gravity Rush what sort of image problems are you experiencing when running the game at native resolution? Will running Gravity Rush at a slightly lower resolution (940 x 524) get rid of the graphical glitches?

As for the game Injustice, if you run the game slightly lower than native resolution, are there still graphical image problems?

**Comment by diegorocha2007** [comment]
Is MSAA doable on Persona 4 Golden? Or a downscaled 1280x720 like Catherine?

**Comment by q6164007** [comment]
P4g can't increase the resolution to 1280x720, only 2x MSAA can be turned on, 4x MSAA will make the game crash, I don't know why.
```
# Persona 4 Golden [US 1.00]
[PCSE00120,eboot.bin,0xB8EBED65]
@IB
1:0xDBCEC fl32(<ib_w>)
1:0xDBCF0 fl32(<ib_h>)
@MSAA
0:0x2B49A0 t1_mov(4,<msaa>)
```

**Comment by diegorocha2007** [comment]
Oh it already makes the game looks better, thank you @q6164007 , you rock!

**Comment by q6164007** [comment]
Gravity Rush's graphics glitch is like having multiple images, at any resolution.
Injustice's graphics glitch is that the health bar has disappeared, at any resolution.
![2019-03-17-093629](https://user-images.githubusercontent.com/48059442/54484236-394e2a00-489d-11e9-8cac-86d1b7a0ac40.png)

**Comment by nad45** [comment]
Could you give us the injustice patchlist please
Even without lifebars i would like to try

**Comment by q6164007** [comment]
Well, I don't think it makes any sense.
```
# Injustice: Gods Among Us Ultimate Edition [EU 1.01]
[PCSB00356,eboot.bin,0x9E662913]
@FB
0:0x841E8 t2_mov(1,2,<fb_w>)
0:0x841EC t2_mov(0,1,<fb_h>)
```

**Comment by Electry** [comment]
I don't see any difference between 2x and no msaa in p4g.

Also, patching fb in injustice doesn't change the internal res iirc. You need to patch ib & region clipping as well.

**Comment by q6164007** [comment]
@Electry Yes, you are right.They don't seem to make any difference，although viewed by VGi is 2x MSAA.Maybe I made a mistake. Do you have any good ideas?
Injustice I just made a simple attempt, and I found that this was not a problem I could solve, so I didn't go any further to do internal resolution patches.

**Comment by Electry** [comment]
No worries. Maybe you could check sceGxmShaderPatcherCreateFragmentProgram() func, it takes an MSAA parameter as well, but that's beyond my understanding.

I appreciate the sheer amount of patches you made. This is great :) I'll add them to the list as soon as I have more free time.

**Comment by eddyfire** [comment]
@Electry Could you share the ones you did for injustice?

**Comment by diegorocha2007** [comment]
@q6164007 Yeah, it's just an illusion I was having on p4g, the native resolution is there, but it seems that the msaa is not enabled. Well, thanks for the effort, much appreciated.

**Comment by Peoples00** [comment]
Can you add Disney Epic Mickey 2: The Power of Two [EU 1.00] PCSF00309?

**Comment by q6164007** [comment]
@Peoples00 It is the same as PCSF00308, you only need to change PCSF00308 to PCSF00309.

**Comment by Peoples00** [comment]
@q6164007 yes I did that, but the frame rate drops, is it possible to stabilize the frame rate?

**Comment by justalex95** [comment]
wanted to post to say @q6164007 and @Electry, you guys have delivered PS3 gaming on the go, tokyo xanadu, fate unbral star, street fighter X tekken, killzone wipeout, ninja gaiden 2, god of war collection and sly are all easily PS3 quality and if I'm honest some of these games surpass it with a few of them at near 60fps and beautiful graphical fidelity on a 5 inch OLED screen. Battery wise, not noticed much of a difference, the brightness is still the killer on that front but, massive thanks to both of you and the other additions from other contributors, I dont need to gamble on a nintendo switch for games that I wouldnt play now, the vita's the most underrated console of all time, great work

**Comment by justalex95** [comment]
> Title	Developer	Framebuffer	Backbuffer	MSAA	Target Framerate
> Ys VIII: Lacrimosa of Dana	Nihon Falcom	960x544	960x512 840x476 720x320	none	30
> ```
> # Ys VIII: Lacrimosa of Dana [EU 1.02]
> [PCSB01128,eboot.bin,0x804268F1]
> # Ys VIII: Lacrimosa of Dana [US 1.02]
> [PCSE01103,eboot.bin,0x804268F1]
> @IB
> 0:0x18A1E2 t2_mov(0,4,<ib_w>)
> 0:0x18A1E6 t2_mov(0,5,<ib_h>)
> 0:0x18A1F0 t2_mov(0,6,<ib_w>)
> 0:0x18A1F4 t2_mov(0,7,<ib_h>)
> 0:0x18A1FA t2_mov(1,4,<ib_w>)
> 0:0x18A202 t2_mov(1,5,<ib_h>)
> 0:0x191798 t2_mov(1,0,<ib_w>)
> 0:0x1917A6 t2_mov(1,0,<ib_h>)
> 0:0x19187A t2_mov(1,1,<ib_w>)
> 0:0x191888 t2_mov(1,1,<ib_h>)
> @FPS
> 0:0x289620 t1_mov(0,<vblank>)
> # Ys VIII: Lacrimosa of Dana [JP 1.02]
> [PCSG00881,eboot.bin,0xC2D25375]
> @IB
> 0:0x188F22 t2_mov(0,4,<ib_w>)
> 0:0x188F26 t2_mov(0,5,<ib_h>)
> 0:0x188F30 t2_mov(0,6,<ib_w>)
> 0:0x188F34 t2_mov(0,7,<ib_h>)
> 0:0x188F3A t2_mov(1,4,<ib_w>)
> 0:0x188F42 t2_mov(1,5,<ib_h>)
> 0:0x190574 t2_mov(1,0,<ib_w>)
> 0:0x190582 t2_mov(1,0,<ib_h>)
> 0:0x190656 t2_mov(1,1,<ib_w>)
> 0:0x190664 t2_mov(1,1,<ib_h>)
> @FPS
> 0:0x285FD0 t1_mov(0,<vblank>)
> # Ys VIII: Lacrimosa of Dana [ASIA 1.02]
> [PCSH00297,eboot.bin,0xB4F97187]
> @IB
> 0:0x189130 t2_mov(0,4,<ib_w>)
> 0:0x189134 t2_mov(0,5,<ib_h>)
> 0:0x18913E t2_mov(0,6,<ib_w>)
> 0:0x189142 t2_mov(0,7,<ib_h>)
> 0:0x189148 t2_mov(1,4,<ib_w>)
> 0:0x189150 t2_mov(1,5,<ib_h>)
> 0:0x1906CA t2_mov(1,0,<ib_w>)
> 0:0x1906D8 t2_mov(1,0,<ib_h>)
> 0:0x1907AC t2_mov(1,1,<ib_w>)
> 0:0x1907BA t2_mov(1,1,<ib_h>)
> @FPS
> 0:0x285834 t1_mov(0,<vblank>)
> ```

@q6164007, this can play at 1280x720 resolution. after tokyo xanadu was able to do it because it was originally upscaled to 544p, I had a random thought it would work with lacrimosa of dana, fps drops from 30 in camp to 22-25 and shows in vitagrafix overlay, so it definitely enforces it, only tried leaving the camp and still plays smoothly enough with 720p setting, looks noticeably smoother as well

**Comment by InitialXKO** [comment]
[图像]


@justalex95, 720p works but when you talk to npc face to face, there will be a black block in the downright corner of screen.
________________________________

**Comment by justalex95** [comment]
@InitialXKO, I tried it just before I went to bed last night so havent tested it much. the black box doesnt bother me that much because it isnt there on the island for most of the time, its on some cutscenes and like you said talking to NPC's

Fate extella freezes in the first level, when you reach the boss intro video as well. I'm sure there would be bugs, but thought it was interesting anyways, it really doesnt seem that far off playing it which is surprising for some games, but chances are it'll be filled with crashes and bugs, to see 720p on the vita though is pretty funny, dont tell nintendo haha

**Comment by justalex95** [comment]
1280x544 fixes most of the issues with y's VIII (the black box is caused by going over 544p) needs more testing though, but looks good. fate: umbral star the resolution seems pretty flexible, might be a memory limit but it seems to have a bit of room for increasing the Y resolution, but the graphics really benefit even @1280x544

**Comment by justalex95** [comment]
ninja gaiden 2 sigma plus works @1280x544 as well havent noticed any bugs or crashes yet

**Comment by TheMostEve** [comment]
How about Metal gear solid hd collection? @q6164007

**Comment by eddyfire** [comment]
@q6164007 do you think u could try injustice IB at 960x544?

**Comment by justalex95** [comment]
played the full arcade mode in street fighter @1600x720 and has never froze or crashed  while playing it any other time

**Comment by justalex95** [comment]
persona 4's vertical resolution is freely changeable.  the horizontal resolution crashes the game. 960x1080 is possible but with a strange slowdown that creates afterimages. 960x720 w/2xMSAA is a good balance

**Comment by ruzzellmarc** [comment]
Hi are you gonna input this thru pc or can i put this on vitashell😅 thank you

**Comment by Dupdon** [comment]
Does anyone have the code for persona 4 eu msaa? Thanks!

**Comment by arzer0ne** [comment]
@q6164007 Can you try to create patch for PCSE01254 Fate Extella Link (US)?

**Comment by Electry** [comment]
I've added everything from this thread to the patchlist. Thank you again.
