### ISSUE TITLE
World of Final Fantasy

### ISSUE THREAD

**Issue by Exia-Ti885** [Electry/VitaGrafixPatchlist#44]
Is this game have a issue? I check supported list games, World of Final Fantasy marked as yellow, but not linked any related issue..is this game work fine? thank you in advance for your answer.

**Comment by Doredialilligan** [comment]
Here you have all the variants that are in the release:
```
# World of Final Fantasy [EU 1.03]
[PCSB00951,eboot.bin]
@IB
0:0x429568 t2_mov(1,1,0x5400000)
0:0x22C9E6 t2_mov(1,5,<ib_w>)
0:0x22C9EC t2_mov(1,0,<ib_h>)

# World of Final Fantasy [US 1.03]
[PCSE00880,eboot.bin]
@IB
0:0x429580 t2_mov(1,1,0x5400000)
0:0x22C9FE t2_mov(1,5,<ib_w>)
0:0x22CA04 t2_mov(1,0,<ib_h>)

# World of Final Fantasy [ASIA 1.03]
[PCSH00223,eboot.bin]
@IB
0:0x429598 t2_mov(1,1,0x5400000)
0:0x22CA16 t2_mov(1,5,<ib_w>)
0:0x22CA1C t2_mov(1,0,<ib_h>)

# World of Final Fantasy [JP ?]
[PCSG00709,eboot.bin]
@IB
0:0x429560 t2_mov(1,1,0x5400000)
0:0x22C9DE t2_mov(1,5,<ib_w>)
0:0x22C9E4 t2_mov(1,0,<ib_h>)
```
And there you have the issue:
https://github.com/Electry/VitaGrafix/issues/15

**Comment by Exia-Ti885** [comment]
Thank you!

**Comment by Electry** [comment]
Not every resolution works, e.g. 720x408 doesn't, so I've marked it with yellow.

960x544 works just fine though. If you want to use anything else, your best bet is to try multiples of 32 for width/height.

**Comment by Exia-Ti885** [comment]
@electry: Thank you! I was try 800x400 and it work fine.
