### ISSUE TITLE
[Bug] The LEGO Movie Videogame [EUR] - native resolution don't work at all :(

### ISSUE THREAD

**Issue by rand92000** [Electry/VitaGrafixPatchlist#49]
![2019-06-01-143310](https://user-images.githubusercontent.com/39204363/58748982-3a482e00-8480-11e9-9438-7df2722e28de.jpg)
![2019-06-01-143426](https://user-images.githubusercontent.com/39204363/58748983-3ae0c480-8480-11e9-8b35-95cf8312e586.jpg)

It should be working now, including all other 16:9 resolutions (840x476, 900x510, etc...)
Closing the issue.

_Originally posted by @Electry in https://github.com/Electry/VitaGrafixPatchlist/issues/1#issuecomment-450892518_

**:(
Now, seems like the similar problem touched The LEGO Movie Videogame [PCSB00553]
Is the fix possible? 
SENDING 2 screenshots comparison when 960x544 is turned on and OFF**
Now running on 3.70 Henkaku. No problems with other games.

**Comment by Electry** [comment]
![2019-12-30-235035](https://user-images.githubusercontent.com/12598379/71603924-7733ea80-2b5f-11ea-8875-34952ef42633.png)
![2019-12-30-234831](https://user-images.githubusercontent.com/12598379/71603926-7a2edb00-2b5f-11ea-80e0-eae276c2a78b.png)

I don't have any problems in PCSB00553.

Closing this. If it still doesn't work for you, please reopen the issue.

**Comment by rand92000** [comment]
Fixed - unfortunately I don't remember what I'd changed though. 
EDIT: Ah, https://github.com/Electry/VitaGrafixPatchlist/issues/1#issuecomment-450892518
so i'd just updated patchlist.txt
