### ISSUE TITLE
Minecraft 1.83 Update

### ISSUE THREAD

**Issue by AmyGrrl** [Electry/VitaGrafixPatchlist#51]
Can you update the patchlist to support the Minecraft v1.83 Update Patch. Thanks!

Also I know this might be outside the scope of this plugin. But would it be possible to increase the draw distance so more chunks get shown on screen? No worries if you can't.

**Comment by SheidCraft** [comment]
https://github.com/Electry/VitaGrafixPatchlist/issues/46#issuecomment-476031551

**Comment by AmyGrrl** [comment]
Thanks. I didn't not think to checked the closed issue list.

**Comment by Electry** [comment]
Updated in https://github.com/Electry/VitaGrafixPatchlist/commit/ca9d6aaafd93d9f8268f7887aba21f8b0214842c
