### ISSUE TITLE
Wipeout 2048

### ISSUE THREAD

**Issue by adrianbass360** [Electry/VitaGrafixPatchlist#53]
Just something I noticed. Changing the resolution to 960x544 is fine. However, changing FPS to 30 or 60 causes your ship to flicker or shake abnormally, both in the scenes before the race and during. Unfortunate you have to leave FPS as off..

**Comment by justalex95** [comment]
Yeah I had this problem as well, try the 444mhz clocks, they seem to reduce it slightly without impacting fps that much

**Comment by adrianbass360** [comment]
You know, I haven't tried that. I'll get back to you in that, thanks!

**Comment by adrianbass360** [comment]
Okay so I messed with the settings a bit more, and changing it to 444mhz does definitely makes your ship shake a lot less, but unfortunately it also gets rids of all the extra frames you get with 500(494)MHz. It drops from ~43fps to only ~34. At that point I rather get rid of all the shaking and keep it at a steady 30fps at native res 😅

**Comment by justalex95** [comment]
ah well, worth a try

**Comment by Electry** [comment]
closing this in favor of issue https://github.com/Electry/VitaGrafixPatchlist/issues/72
