### ISSUE TITLE
Minecraft Transparent Blocks Bug

### ISSUE THREAD

**Issue by KronoTrigger** [Electry/VitaGrafixPatchlist#55]
The transparent blocks in Minecraft 1.83 show dark lines if the game is set to a resolution higher than its default resolution. It’s mostly the dyed transparent blocks like Slime, Dyed Glass, ect.

**Comment by AmyGrrl** [comment]
I'm having this problem as well. I wondered if using a slightly lower resolution might fix the problem.

**Comment by razortotal** [comment]
Hey man, my VitaGrafix Configurator showing that MC 1.83 is not supported and it's disabled

**Comment by AmyGrrl** [comment]
> 
> 
> Hey man, my VitaGrafix Configurator showing that MC 1.83 is not supported and it's disabled

If you took the time to look on this page you would find the updated code for MC 1.83.

**Comment by AmyGrrl** [comment]
Thanks Electry for the updated code to fix the transparent blocks bug. I tried to use the new code but the game does not boot. Using MC 1.83 US Version. Having looked at the updated code list it appears a newer version of VitaGrafx is required to use the fix. Looking forward to using this fix when that version comes out. Thanks.

**Comment by Electry** [comment]
Fixed in https://github.com/Electry/VitaGrafixPatchlist/commit/ca9d6aaafd93d9f8268f7887aba21f8b0214842c
