### ISSUE TITLE
Request I'm setsuna 

### ISSUE THREAD

**Issue by Jsbach90** [Electry/VitaGrafixPatchlist#63]
Anybody here can upload patch I'm setsuna?

**Comment by swosho** [comment]
Why bother? It runs at native resolution as it is.

**Comment by q6164007** [comment]
Title | Developer | Framebuffer | Backbuffer | MSAA | Target Framerate
-- | -- | -- | -- | -- | --
I am Setsuna | Tokyo RPG Factory | 960x544 | 960x544 | none | 30

```
# I am Setsuna [JP 1.00]
[PCSG00756,eboot.bin,0x89B603C7]
@FPS
0:0x186F4 a1_mov(0,0,<vblank>)
```

**Comment by Electry** [comment]
added in https://github.com/Electry/VitaGrafixPatchlist/commit/0beb5adf0a9a442c1b2c8e3188dc6470fae3f695
