### ISSUE TITLE
amazing spiderman, menu fix

### ISSUE THREAD

**Issue by justalex95** [Electry/VitaGrafixPatchlist#71]
found a way to run native res without the menu crashing

https://github.com/Electry/VitaGrafix/issues/122

**Comment by SheidCraft** [comment]
Does not work on European [PCSB00428]

**Comment by Littlesquee90** [comment]
How weird it looks! But it works. And yes, resolution takes the effect. Though not very much but then, you can't have everything. And yeah, its the US version I tried.

**Comment by SheidCraft** [comment]
But are there screenshots for comparison?

**Comment by justalex95** [comment]
still doesnt fix the weird bug on the first boss where you cant progress but its strange it somehow lets the menu work when it shouldnt be recognised or have an effect

**Comment by swosho** [comment]
The difference is very subtle when compared side-by-side: 
![2019-10-18-085706](https://user-images.githubusercontent.com/5187034/68343605-db08dc80-00f5-11ea-90da-74c9c2a45056.jpg) ![2019-10-18-090209](https://user-images.githubusercontent.com/5187034/68343623-e3f9ae00-00f5-11ea-8b83-cbff23aff761.jpg)

The game works fine from start to finish this way, I've made a few screenshots while playing through: [imgur album](https://imgur.com/a/WfXrLxB)

**Comment by Littlesquee90** [comment]
Just reporting how it goes when you progress in the game a bit. 
Some levels still look better. And others really bad. In some places framedrops could also be very frustrating. The thrill of the hunt plays really bad. But the open-world level right after called To Smash the Spider actually looks and plays well. Generally during the web-swinging in the open-world and doing side-missions, you can still note a difference in graphics, the greyishness diminishes a bit. Buildings' edges look sharper. The texture of Spider suit does not look as pixelated. 
MSAA like Most Wanted's would have been nice!

**Comment by justalex95** [comment]
hey guys, try a proper fix by electry [here](https://github.com/Electry/VitaGrafix/issues/122#issuecomment-557811766)

**Comment by Electry** [comment]
fixed in https://github.com/Electry/VitaGrafixPatchlist/commit/11f155bc29c43c33e6bf23f3ce0fef684a1ea558
