### ISSUE TITLE
Uncharted golden abyss chapter 8

### ISSUE THREAD

**Issue by kuczi55** [Electry/VitaGrafixPatchlist#74]
Game crashes in chapter 8 (Error code: C2-12828-1), when playing in native resolution. Chapter 7 played well without any crashes.

**Comment by Electry** [comment]
can you send me dumped gamesave? preferably using https://github.com/d3m3vilurr/vita-savemgr/releases

**Comment by kuczi55** [comment]
I've send you link to save on your e-mail. If there would be any problems let me know.

**Comment by EnekoT2001** [comment]
I have a savefile with the game finished, if it's useful for debugging or anything let me know, i can also test some areas with my vita since i also have vitagrafix, i tested the last chapter yesterday with native res and it was working perfectly (tho according to psvshell that game takes up every last MB of ram possible lol)

**Comment by Electry** [comment]
Looks like that mempool I shrunk by 7mb is used almost in its entirety in Chapter 8.

[PCSF00001.txt](https://github.com/Electry/VitaGrafixPatchlist/files/4009950/PCSF00001.txt)
Try this, if this still crashes in some other chapter, we might need to figure out a way to get those few mbs of vram from elsewhere.

**Comment by EnekoT2001** [comment]
I tested chapter 8 with the old and this new patch and it crashes in both, it happens at the cutscene from the beginning of chapter 8 (i tried using different clock speeds too and makes no difference). I also tried skipping the cutscene but i can't, the skip cutscene text is greyed out with a "(loading data)" next to it, also, it ends up crashing as well :c 

About finding extra vram memory, using VGi i found out that a render target uses MSAA 4x, as far as i know msaa is very memory intensive, tho i know that changing msaa settings is a headache so idk...
Its totally a bummer, using native res and max clock speeds the game looks and plays like a remaster tbh

**Comment by kuczi55** [comment]
Last time I skipped cutscene disabling vitagrafix but game still was crushing on the beginning of chapter 8. Now I run game with new patch and it looks fine, no crushing for now. Unfortunatelly I don't have save with last cutscene of chapter 7, so I can't say if it still crashes here. But right after this cutscene it seems to work.

**Comment by Electry** [comment]
Try replacing

```
0:0x22B56A t2_mov(1, 3, 0x5100000 - 4 * 1024 * 1024)
0:0x219706 mov32(1, 0x1b9c000 - 4 * 1024 * 1024, 2)
0:0x2155B4 t2_mov(1, 1, 0xE00000 - 3 * 1024 * 1024)
```
with
```
0:0x22B56A t2_mov(1, 3, 0x5100000 - 3 * 1024 * 1024)
0:0x219706 mov32(1, 0x1b9c000 - 3 * 1024 * 1024, 2)
0:0x2155B4 t2_mov(1, 1, 0xE00000 - 4 * 1024 * 1024)
```
if still crashes, try - 2, - 2, - 5

I wish it ran better though, 20 fps dips aren't all fun.

**Comment by kuczi55** [comment]
After replacing

0:0x22B56A t2_mov(1, 3, 0x5100000 - 4 * 1024 * 1024)
0:0x219706 mov32(1, 0x1b9c000 - 4 * 1024 * 1024, 2)
0:0x2155B4 t2_mov(1, 1, 0xE00000 - 3 * 1024 * 1024)
with

0:0x22B56A t2_mov(1, 3, 0x5100000 - 3 * 1024 * 1024)
0:0x219706 mov32(1, 0x1b9c000 - 3 * 1024 * 1024, 2)
0:0x2155B4 t2_mov(1, 1, 0xE00000 - 4 * 1024 * 1024)

I was able to finish chapter 8 (last time game crashed in the last sequence of chapter 8 - when you ned to defeat guy who attackted Chase), but still don't know if game still crashes in the last cutscene of chapter 7.

**Comment by kuczi55** [comment]
I've checked this cutscene and it still crashes (also trying - 2, - 2, - 5).

**Comment by Electry** [comment]
I didn't want to cut into parameter buffer that much, but ¯\_(ツ)_/¯
Go - 0, - 0, - 7. That should 100% work.

**Comment by kuczi55** [comment]
Yes, it works, thank you for your work

**Comment by EnekoT2001** [comment]
> I didn't want to cut into parameter buffer that much, but ¯_(ツ)_/¯
> Go - 0, - 0, - 7. That should 100% work.

Just tried and it works, thanks!!

**Comment by Fershock** [comment]
could you change the file for an updated one? I would do it myself but I don't understand it, I'm sorry

**Comment by kuczi55** [comment]
> could you change the file for an updated one? I would do it myself but I don't understand it, I'm sorry

In the PCSF00001.txt from this thread
change
0:0x22B56A t2_mov(1, 3, 0x5100000 - 4 * 1024 * 1024)
0:0x219706 mov32(1, 0x1b9c000 - 4 * 1024 * 1024, 2)
0:0x2155B4 t2_mov(1, 1, 0xE00000 - 3 * 1024 * 1024)
with

0:0x22B56A t2_mov(1, 3, 0x5100000 - 0 * 1024 * 1024)
0:0x219706 mov32(1, 0x1b9c000 - 0 * 1024 * 1024, 2)
0:0x2155B4 t2_mov(1, 1, 0xE00000 - 7 * 1024 * 1024)

**Comment by Electry** [comment]
> could you change the file for an updated one?

done

**Comment by Fershock** [comment]
Thanks a lot!
