### ISSUE TITLE
Break compatibility with vitagrafix configurator

### ISSUE THREAD

**Issue by oldskool978** [Electry/VitaGrafixPatchlist#75]
```
An error occurred:
[string"?"]:622:attempt to index a nil value
```

VitaGraphix configurator seems incompatible with latest patchlist.

**Comment by SirMrMister** [comment]
Can confirm that I'm getting the same error when launching the configurator since I updated the patchlist.

**Comment by oldskool978** [comment]
fixed on latest release of configuration
