### ISSUE TITLE
Disney Epic Micky 2 PCSF00309

### ISSUE THREAD

**Issue by Peoples00** [Electry/VitaGrafixPatchlist#76]
hello is it possible to increase the graphics or more stable frames?

**Comment by SheidCraft** [comment]
@Peoples00 Yes, it possible. With a resolution of 640x368, the game runs at 25-30fps, which is quite playable.  The picture remains almost unchanged.

**Comment by Peoples00** [comment]
That would be awesome

**Comment by SheidCraft** [comment]
@Peoples00 Well, I've been playing like this for a long time and this really awesome

**Comment by Peoples00** [comment]
Since you're right I play it every now and then but in some places it jerky and I play it on the PSTV

**Comment by SheidCraft** [comment]
@Peoples00 oh ... Well, one can only hope that someone will be able to find a way to run games with a lot of RAM

**Comment by Peoples00** [comment]
someone will surely do that

**Comment by Peoples00** [comment]
can you add that to the patchlist?
