### ISSUE TITLE
[Issue] - Street Fighter X Tekken

### ISSUE THREAD

**Issue by nad45** [Electry/VitaGrafixPatchlist#81]
Hi
I can't run the game at native resolution since the Vitagrafix 5.0 version, it was working perfectly before

An error occured while reading config file
NID : 0x4C4DB951
Failed to parse config (line 1146, pos0)

Here's my line 1146 : [PCSB00144,eboot.bin,0x4C4DB951]
Someone have an idea?

**Comment by EnekoT2001** [comment]
try downloading the patch list and rewriting the one you have
( go to https://raw.githubusercontent.com/Electry/VitaGrafixPatchlist/master/patchlist.txt right click the text > save as... > patchlist.txt)
Also remember to use the latest Vitagrafix as this patchlist requires VG 5.0.1+

**Comment by nad45** [comment]
Lol
I'm f.... dumb, i need to sleep
Issue Solved
i put the patchlist lines in the config.txt file, of course it wasn't working..
Thanks for you help @EnekoT2001

**Comment by EnekoT2001** [comment]
No problem, I also make these kinda mistakes all the time, and happy to have helped you :D
