### ISSUE TITLE
Oversized minimap | Fantasy Hero: Unsigned Legacy

### ISSUE THREAD

**Issue by swosho** [Electry/VitaGrafixPatchlist#84]
![2020-02-08-031348](https://user-images.githubusercontent.com/5187034/74082028-65970a00-4a5e-11ea-9d48-2c2dc4e76ace.png)
Everything else is scaled correctly, including the full-sized map.
I'm also using this opportunity to say thanks for the patch!

**Comment by Electry** [comment]
Thanks for letting me know.

Try adding
```
0:0x56A00 mov32  (0, 0.305 * (736.0 / align(fb_w, 32)), 4)
0:0x569EE t3_mov (1, 0.310 * (416.0 / align(fb_h, 32)) & 0xffff)
0:0x56A0C t1_movt(1, 0.310 * (416.0 / align(fb_h, 32)) >> 16)
```
to the patch for Fantasy Hero, anywhere is fine. This is for EU/US regions, lmk if you need JP/ASIA.

**Comment by swosho** [comment]
That did the trick:
![2020-02-08-173537-1](https://user-images.githubusercontent.com/5187034/74088052-b88eb280-4a9a-11ea-833a-7fb853378535.jpg)
Thanks!
